# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: redcarpet

highlighter: pygments
paginate: 20 # pagination based on number of posts
paginate_path: "page/:num"

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
categories_path : categories.html
tags_path : tags.html

BASE_PATH : http://lovexiaohuangdou.github.io/blog
baseurl: /blog
title : 小黄豆的blog



author:
  name: Ankan Biswas
  role: 小黄豆
  email: zhaoyunpan123@sina.com
  github: lovexiaohuangdou
  twitter: talk2ankan
  facebook: talk2ankan
  googleplus: +AnkanBiswasWorkspace
  bio: "宁静致远，淡泊明志"
  uno-dbyll: "/blog/assets/media/lamp.jpg"
